### ISSUE TITLE
"evaluation_scripts_squad_v2" was not found

### ISSUE THREAD

**Issue by xinykou** [ellaneeman/disent_qa#1]
Hello,
         Thank you very much for this implementation.
         The path for package "imprt  evaluation_scripts_squad_v2  as ev" in the ./evaluate.py file was not found.
Best, 
Xiny

**Comment by taifyang** [comment]
> Hello, Thank you very much for this implementation. The path for package "imprt evaluation_scripts_squad_v2 as ev" in the ./evaluate.py file was not found. Best, Xiny

could you tell me how you solve the problem?
